version: "3"

services:
  stocks:
    image: ${DTR}/finance_stocks:${ENV}-${BUILD_NUMBER}
    ports:
      - "5000"

  populate_stock_table:
    image: ${DTR}/finance_populate_stock_table:${ENV}-${BUILD_NUMBER}
    depends_on:
      - stocks
    environment:
      - STOCK_URL=http://stock:5000

