version: "3"

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=banana
      - MYSQL_DATABASE=stock

  stock_table:
    image: ${DTR}/finance_stock_table:${ENV}-${BUILD_NUMBER}
    depends_on:
      - mysql
    ports:
      - "5000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PASSWORD=banana
      - MYSQL_PORT=3306

  stock_spreadsheet:
    image: ${DTR}/finance_stock_spreadsheet:${ENV}-${BUILD_NUMBER}
    ports:
      - "5000"

